service: basic-app

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

custom:
  serverless-nextjs:
    nextConfigDir: ./
    routes:
      - src: post
        path: post/{slug}
        request:
          parameters:
            paths:
              slug: true

package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**
