sudo: false
os:
  - windows
  - linux
  - osx
language: node_js
node_js:
  - "8"
  - "11.10"
install:
  - npm install
  - npm install --prefix integration/app-with-serverless-offline
script:
  - npm run lint
  - npm test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run coveralls; fi
  - npm run integration
