nextApp:
  component: ../../
  inputs:
    cloudfront:
      # the cache settings below will be applied to the CloudFront distribution
      # the pages will be cached at CloudFront's edge locations
      /post/*:
        ttl: 86400    # 1 day cache
      /about:
        ttl: 31536000 # 1 year

