service: basic-next-serverless-app

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512

stage: dev
region: eu-west-1

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

custom:
  serverless-nextjs:
    nextConfigDir: ./
    staticDir: ./assets
    routes:
      - src: ./assets/robots.txt
        path: robots.txt
      - src: post
        path: post/{slug}
        request:
          parameters:
            paths:
              slug: true

package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**
